# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e7de58fe781af83ed6b7f33bc8ff6e2"
name = "first-pp"
application_url = "https://release-brazilian-parenting-renew.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "akash-test-store34.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_product_listings,read_products,write_customers,write_products"

[auth]
redirect_urls = [
  "https://release-brazilian-parenting-renew.trycloudflare.com/auth/callback",
  "https://release-brazilian-parenting-renew.trycloudflare.com/auth/shopify/callback",
  "https://release-brazilian-parenting-renew.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
